sudo: required
language: generic
services:
  - docker

install:
  - sed -i -n '/FROM conex.eff.org/q;p' Dockerfile
  - docker build -t app .

script:
  - docker run app npm run lint
  - docker run app bin/test

