language: node_js
dist: focal
node_js:
    - "node"

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.68.3/hugo_extended_0.68.3_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  - npm install

cache:
  directories:
    - "node_modules"

script: npm run lint && hugo
