DefaultContentLanguage = "en"
baseURL = "https://privacybadger.org"
title = "Privacy Badger"

[params]
  badgerVersion = "2019.11.18"
  matomoID = 36

[languages]
  [languages.en]
    LanguageName = "English"
    weight = 1
  [languages.es]
    LanguageName = "Español"
    weight = 2
  [languages.zh-CN]
    LanguageName = "中文（中国）"
    weight = 3
