DefaultContentLanguage = "en"
baseURL = "https://privacybadger.org"
title = "Privacy Badger"

[params]
  badgerVersion = "2019.11.18"
  matomoID = 36

[languages]
  [languages.en]
    LanguageName = "English"
    weight = 1
  [languages.es]
    LanguageName = "Español"
    weight = 2

[markup.goldmark.renderer]
  unsafe= true
