DefaultContentLanguage = "en"
baseURL = "https://privacybadger.org"
title = "Privacy Badger"

[params]
  badgerVersion = "2019.11.18"
  matomoID = 36

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 1
  [languages.de]
    contentDir = "content/de"
    languageName = "Deutsch"
    weight = 2
  [languages.es]
    contentDir = "content/es"
    languageName = "Español"
    weight = 3
  [languages.fr]
    contentDir = "content/fr"
    languageName = "Français"
    weight = 4
  [languages.ru]
    contentDir = "content/ru"
    languageName = "Русский"
    weight = 5
  [languages.sv]
    contentDir = "content/sv"
    languageName = "Svenska"
    weight = 6
  [languages.tr]
    contentDir = "content/tr"
    languageName = "Türkçe"
    weight = 7
  [languages.zh-CN]
    contentDir = "content/zh_CN"
    languageName = "中文（中国）"
    weight = 8

[markup.goldmark.renderer]
  unsafe= true
