DefaultContentLanguage = "en"
baseURL = "https://privacybadger.eff.org"
title = "Privacy Badger"

[params]
  badgerVersion = "2019.2.19"
  matomoID = 36

[languages]
  [languages.en]
    weight = 1
  [languages.fr]
    weight = 2
  [languages.es]
    weight = 3
