#!/usr/bin/env bash

echo "# GENERATED BY genconf.sh, DO NOT EDIT MANUALLY"
echo

# generate the locales line
echo -n "[po4a_langs]"
for po_file in po/faqs.*.po; do
  locale_code="${po_file#po/faqs.}" # strip prefix
  locale_code="${locale_code%.po}" # strip suffix
  echo -n " $locale_code"
done
echo

# misc. options
cat << EOF

[po4a_paths] po/faqs.pot \$lang:po/faqs.\$lang.po

[options] opt:"--addendum-charset=UTF-8" opt:"--localized-charset=UTF-8" opt:"--master-charset=UTF-8" opt:"--master-language=en" opt:"--msgmerge-opt='--no-wrap'" opt:"--porefs=file" opt:"--wrap-po=newlines"

[po4a_alias:markdown] text opt:"--option markdown" opt:"--option yfm_keys=question" opt:"--addendum-charset=UTF-8" opt:"--localized-charset=UTF-8" opt:"--master-charset=UTF-8" opt:"--keep=100" opt:"--option neverwrap" opt:"--option nobullets"

EOF

# Get category order from data/faq.toml
declare -A category_index
rank=0
while read category; do
    category_index["$category"]=$rank
    ((rank++))
done < <(sed -n '/categories = \[/,/\]/p' data/faq.toml | tr -d '[],"')

# Generate the list of FAQ entries, sorted by category and weight
for faq_file in content/en/faqs/*.md; do
    weight=$(grep -m 1 '^weight:' "$faq_file" | awk '{print $2}')
    category=$(grep -m 1 '^category:' "$faq_file" | awk '{print $2}')
    category_rank=${category_index[$category]}
    # Format: 01-0230 content/en/faqs/*.md
    printf "%02d-%04d %s\n" "$category_rank" "$weight" "$faq_file"
done | sort | while read _sort_keys faq_file; do
    echo "[type: markdown] $faq_file \$lang:content/\$lang/faqs/$(basename "$faq_file")"
done
