name: Build

on:
  push:
    branches:
      - master
      - github-actions
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -q -t app .
          sed -i -n '/FROM conex.eff.org/q;p' Dockerfile

      - name: Run lint 
        run: docker run app npm run lint